[package]
name = "replicache-client"
version = "0.1.0"
authors = ["Rocicorp <replicache@roci.dev>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
wee_alloc = "0.4.5"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
