[package]
name = "replicache-client"
version = "0.1.0"
authors = ["Rocicorp <replicache@roci.dev>"]
edition = "2018"

[dependencies]
data-encoding = "1.1.1"
sha2 = "0.8.1"
wasm-bindgen = "0.2"
wee_alloc = "0.4.5"

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'  # Optimize for size.
panic = "abort"
