name = "paint-fight2"
main = "demo/worker/index.ts"
compatibility_date = "2022-11-30"
account_id = "085f6d8eb08e5b23debfb08b21bda1eb"

[build]
# don't watch all resources because whenever the server restarts we have to
# create a new room
watch_dir = "demo/worker"

[durable_objects]
bindings = [
  { name = "roomDO", class_name = "RoomDO" },
  { name = "authDO", class_name = "AuthDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["Server"]

[[migrations]]
tag = "v2"
renamed_classes = [{from = "Server", to = "RoomDO" }]
new_classes = ["AuthDO"]

[triggers]
crons = [ "*/5 * * * *" ] # ever 5 mins for AuthDO connection revalidation

#[secrets]
#DATADOG_API_KEY
#REFLECT_AUTH_API_KEY
